/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package comparisons;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;

public class AppTest {
    private List<Movie> movies;

    @BeforeEach
    void setUp() {
        movies = List.of(
                new Movie("The Shawshank Redemption", 1994, List.of("Drama")),
                new Movie("A Beautiful Mind", 2001, List.of("Drama", "Biography")),
                new Movie("Avatar", 2009, List.of("Action", "Adventure", "Fantasy")),
                new Movie("Inception", 2010, List.of("Action", "Adventure", "Sci-Fi")),
                new Movie("Pulp Fiction", 1994, List.of("Crime", "Drama")),
                new Movie("Anchorman", 2004, List.of("Comedy"))
        );
    }

    @Test
    void testSortMoviesByYear() {
        List<Movie> sortedMovies = App.sortMoviesByYear(movies);
        assertEquals(1994, sortedMovies.get(0).getYear());
        assertEquals(1994, sortedMovies.get(1).getYear());

    }

    @Test
    void testSortMoviesByTitleIgnoringPrefix() {
        List<Movie> sortedMovies = App.sortMoviesByTitleIgnoringPrefix(movies);
        assertEquals("Anchorman", sortedMovies.get(0).getTitle());
        assertEquals("Avatar", sortedMovies.get(1).getTitle());

    }
}
