/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge;

public class App {

    private static void merge(int[] left, int[] right, int[] arr){
        int i,j,k;
        i=j=k=0;
        int lLength=left.length;
        int rLength =right.length;
        while (i<lLength && j<rLength){
            if(left[i]<right[j]){
               arr[k++]= left[i++];
            }
            else{
                arr[k++]=right[j++];
            }
        }
        while(i < lLength){
            arr[k++]= left[i++];
        }
        while(j < rLength){
            arr[k++]=right[j++];
        }
    }

    public static void mergeSort(int[] arr) {
        int n = arr.length;
        if (n > 1) {

            int mid = n / 2;
            int[] left = new int[mid];
            int[] right = new int[n - mid];


            for (int i = 0; i < mid; i++) {
                left[i] = arr[i];
            }
            for (int i = mid; i < n; i++) {
                right[i - mid] = arr[i];
            }


            mergeSort(left);
            mergeSort(right);


            merge(left, right, arr);
        }
    }
    public static void main(String[] args) {


        int []arr = new int[]{8,4,23,42,16,15};
        for(int i = 0 ;i<arr.length; i++){
            System.out.print(arr[i]+" ");

        }
        System.out.println(" ");

        mergeSort(arr);
        for(int i = 0 ;i<arr.length; i++){
            System.out.print(arr[i]+" ");

        }

    }
}
