/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package animal;

public class App {

    public static void main(String[] args) {
        Animal a1 = new Animal("cat","max");
        Animal a2 = new Animal("dog","max1");
        AnimalShelter q1=new AnimalShelter();
        q1.enqueue(a1);
        q1.enqueue(a2);

        System.out.println(q1.dequeue("cat").getName());
        System.out.println(q1.dequeue("dog").getName());
        System.out.println(55);

    }
}
