/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package brackets;
import java.util.Stack;
public class App {


    public static void main(String[] args) {
        System.out.println(validateBrackets("[[(mn.),m)]"));
    }
    public static boolean validateBrackets(String str) {  //this works when the sentence contains anything also regards brackets
        Stack<Character> stack = new Stack<>();
        char[] characters = str.toCharArray();
        for(char character: characters) {
            if((int) character ==40 || (int) character ==41 || (int) character ==91 || (int) character == 93 || (int) character == 123 || (int) character ==125) {
                if(character=='{' ||
                        character=='(' ||
                        character=='[')
                    stack.push(character);
                else {
                    if(stack.isEmpty())
                        return false;
                    else if( (stack.peek()=='{' && character=='}') ||
                            (stack.peek()=='(' && character==')') ||
                            (stack.peek()=='[' && character==']') )
                        stack.pop();
                    else
                        return false;
                }
            }
        }
        return stack.isEmpty();
    }
}
