/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binary.tree;

import java.util.ArrayList;
import java.util.List;

public class App {


    public static void main(String[] args) {

        BinarySearchTree tree = new BinarySearchTree();

       tree.add(5);
        tree.add(4);
        tree.add(6);
        tree.add(5);


        System.out.println(tree.Contains(4));



    }
}
