/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binary.tree;

import java.util.ArrayList;
import java.util.List;

public class App {


    public static void main(String[] args) {

        BinarySearchTree tree = new BinarySearchTree();

       tree.addR(10);
        tree.addR(4);
        tree.addR(6);
        tree.addR(3);
        tree.addR(15);
        tree.addR(16);
        tree.addR(11);



        System.out.println(BinarySearchTree.bfs(tree));



    }
}
