package stack;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.lang.*;


public class App {

    public static void main(String[] args) {

        Stack st = new Stack();
//        st.pop();
        st.push(5);
        st.push(4);
        st.push(3);
        System.out.println(st.peek());
        st.pop();
        System.out.println(st.peek());
        st.pop();
        System.out.println(st.peek());
    }
}
